name: 'Install CDK'
description: 'Installs CDK CLI client'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g aws-cdk
      shell: bash
